# Generated by Django 3.1 on 2020-08-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200821_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_locate',
            field=models.BooleanField(choices=[(0, '新校区'), (1, '老校区')], max_length=1, verbose_name='藏书位置'),
        ),
    ]
