# Generated by Django 3.1 on 2020-08-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200821_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='videos',
            field=models.TextField(default='None', null=True, verbose_name='视频链接'),
        ),
    ]
