# Generated by Django 3.1 on 2020-08-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200821_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='videos',
            field=models.TextField(default=1, null=True, verbose_name='视频链接'),
        ),
    ]
